### PR TITLE
Add Photo and Bio -- Jake

### LINKED ISSUE #17: Add Profile Picture and Bio -- Jake

### PR DESCRIPTION
**Pull request by par4a**

### CODE REVIEW

**Review by Funtime60 — COMMENTED** [review]
Did you mean to make the sentences separate paragraphs? If so you should probably use separate paragraph tags. My code should handle it if you're worried about that.

**Comment by par4a** [comment]
Nope. I just wrote it on multiple lines for legibility. Its one paragraph. @Funtime60

**Comment by Funtime60** [comment]
I can't remember how html handles that and I can't test it now, but if it renders it as a single paragraph then I can approve it on your word. This isn't graded.

**Comment by par4a** [comment]
Anything inside the p tags will be a single paragraph regardless of the line it is on.

**Comment by Funtime60** [comment]
Roger that! Will merge. Sorry for the interrogation.

**Review by Funtime60 — APPROVED** [review]

**Pull request merged**
