### PR TITLE
Creates and implements navbar.html

### LINKED ISSUE #6: navbar file and implementation

### PR DESCRIPTION
**Pull request by par4a**

### CODE REVIEW

**Comment by par4a** [comment]
I beleive the code is correct but can't get it to open correctly in the browser. I don't know how to open php code in the broswer through VS code

**Comment by Funtime60** [comment]
We'll need to load it onto a CS machine.

**Comment by par4a** [comment]
> We'll need to load it onto a CS machine.

That is the only way I can think of doing it effectively too.

**Comment by Funtime60** [comment]
You or me?

**Comment by Funtime60** [comment]
I'm going to assume this is as intended and merge it

**Pull request merged**
